### PR TITLE
Add SARIF support

### PR DESCRIPTION
**Pull request by shaopeng-gh**
Add support for output in SARIF format.

About SARIF format:
https://sarifweb.azurewebsites.net/

### CODE REVIEW

**Comment by asottile** [comment]
this would probably be better done as a flake8 plugin rather than pycodestyle (which would help more broadly)

**Comment by sigmavirus24** [comment]
I agree with @asottile

**Comment by EasyRhinoMSFT** [comment]
Hello @asottile @sigmavirus24 if we add SARIF output support to flake8, would that capability then be available to pycodestyle? IOW, does pycodesyle make use of flake8?

**Comment by asottile** [comment]
flake8 runs pycodestyle, yes

**Comment by sigmavirus24** [comment]
> Hello @asottile @sigmavirus24 if we add SARIF output support to flake8, would that capability then be available to pycodestyle? IOW, does pycodesyle make use of flake8?

Flake8 runs pycodestyle, not the other way around

**Comment by EasyRhinoMSFT** [comment]
I see, thanks for clarifying. I'll create an issue in the flake8 repo to get us started.

**Comment by asottile** [comment]
that's the beauty of flake8, you don't have to! you can write your own formatter plugin

**Comment by sigmavirus24** [comment]
@EasyRhinoMSFT an example is [PyCQA/flake8-json](/PyCQA/flake8-json) for formatting things via plugin. It might be a good place to fork from too for a flake8-sarif plugin that y'all can maintain and publish independently

**Comment by EasyRhinoMSFT** [comment]
Thank you both again for your quick replies. Would either of these arrangements be possible?
Add our format to the flake8-json formatter (SARIF is a JSON schema)
or
Create a new repo under PyCQA

We think it makes the most sense to have our formatter as close to flake8 as possible.

Once our formatter is complete, you can publish GitHub workflows for your linters that are configured to use the SARIF formatter. We would be happy to create the workflow YML for you.
Publishing the workflow in your repos enables you to easily update the linter version when you do releases. You can also add entries to the [workflows page](https://github.com/topics/github-workflows), then add the topic to each repo to advertise.

**Comment by sigmavirus24** [comment]
> Thank you both again for your quick replies. Would either of these arrangements be possible?
> Add our format to the flake8-json formatter (SARIF is a JSON schema)

I don't think it's a fit there.

> or
> Create a new repo under PyCQA

That's possible, but you would be the person maintaining it, not Anthony or me.

> We think it makes the most sense to have our formatter as close to flake8 as possible.

Most flake8 plugins are nowhere near it. It's unnecessary to keep things close.

> Once our formatter is complete, you can publish GitHub workflows for your linters that are configured to use the SARIF formatter. We would be happy to create the workflow YML for you.

Why would we bother? We don't need that output

> Publishing the workflow in your repos enables you to easily update the linter version when you do releases. You can also add entries to the [workflows page](https://github.com/topics/github-workflows), then add the topic to each repo to advertise.

What's the point of triggering new releases when flake8 releases when no other plugin needs to do this. We're not maintaining this for you, it probably doesn't need updates and we have no use for it ourselves.

**Comment by EasyRhinoMSFT** [comment]
We would appreciate the creation of a repo called flake8-sarif under PyCQA.

Regarding workflows, the benefit is to increase usage of your linters by making them available for build-time static analysis scanning to every repo on GitHub. SA tools are required to output results in the SARIF format. One of our goals with this effort is to increase the usage of SARIF, so adding a formatter to flake8 and creating the workflows is mutually beneficial.

When I mentioned releases, I meant releases of flake8. When that occurs, workflows that use it should have their version dependency updated accordingly. This would be most reliably done on your side because you are the ones creating the release. If we are responsible, we may not be aware of a release, which could be disadvantageous in the case of security vulnerabilities for example.

**Comment by shaopeng-gh** [comment]
in addition to @EasyRhinoMSFT's question above, after we settle the repo location, this is the code we are looking to use in the target repo currently: https://github.com/shaopeng-gh/flake8-sarif/pull/1
let me know if we are heading at the right direction, thanks!

**Pull request closed without merging**
