### PR TITLE
Python 3.6 invalid escape sequence deprecation fix

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by scop** [comment]
Added a link to the Python 3.6 release notes section that has the explanation. The effect is the same as with deprecated features in general, a warning will be emitted if deprecation warnings are enabled. I don't think that needs to be explained in the commit message.

**Comment by sigmavirus24** [comment]
> I don't think that needs to be explained in the commit message.

Links break. At the very least, please quote the relevant section

```
A backslash-character pair that is not a valid escape sequence now generates a DeprecationWarning. Although this will eventually become a SyntaxError, that will not be for several Python releases.
```

**Comment by scop** [comment]
(Just a ping to note that the requested changes have been done here a while ago...)

**Comment by sigmavirus24** [comment]
Sorry about that @scop. Thanks for addressing that! :cake:

**Pull request merged**
