### PR TITLE
complain about missing space before opening parentheses of import statement

### PR DESCRIPTION
**Pull request by rogalski**
Solves issue #489.

This checker may be better suitable for E2xx category (whitespace issues). Maybe even it should be connected to E221. I'll be happy to change if code review would settle for this alternative.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I don't think this should be E403. This seems to fit better in with E229. Do you agree @IanLee1521?

**Comment by IanLee1521** [comment]
I like E2xx better than E4xx, seems like it should be E275. I also wonder if the wording should be better as "missing whitespace after keyword" to match that family.

**Comment by rogalski** [comment]
Hello, I've fixed commit based on your comments. Is any other action required from me right now?

**Comment by sigmavirus24** [comment]
I don't think so. I'm :+1: on merging this.

**Comment by IanLee1521** [comment]
Looks great! Thanks @rogalski !

**Pull request merged**
