### PR TITLE
Print 0 when using --count and there are no violations

### PR DESCRIPTION
**Pull request by kampde**
Right now nothing is printed if there are no violations

### CODE REVIEW

**Comment by sigmavirus24** [comment]
So, I've thought about this for a short while. This kind of makes sense since your asking for the count and the help text for the option is ambiguous. (At least, I had always read it as "Print the count [if the count is non-zero] and exit 1 [if the count is non-zero].) So perhaps, this needs to be written less ambiguously. That said, I can imagine people relying on the absence of output in CI tooling right now to signal whether or not there's a problem (regardless of exit code). And this will break those people's expectations. Since this is a **breaking change**, I would rather the project hold off on this until 2.0.0 (if the project decides to merge this at all.)

**Comment by kampde** [comment]
Hmmm I hadn't thought of it as a breaking change, but I kind of agree it is. Also, I think that not outputting anything anything even though I am asking for the count it is rather odd.

Anyways, whatever the project decides about merging (or when to merge) this is ok by me, my CI builds can handle both cases now :)

**Comment by petsuter** [comment]
+1
The current behavior is somewhat confusing e.g. when calling pep8 as an external tool from an IDE.

How about at least printing ``0`` when both ``-v`` and ``--count`` are passed?

**Comment by IanLee1521** [comment]
I rebased the branch to fix the merge conflicts (06fcbbc624aba51a875c7317b59137efd6e20024 and ef44231707e77cca9548aa0f7f74a9e1022fb6ea). This was missed in the 2.0 release. I'm debating releasing it as part of the 2.1 release anyways despite the potential issue with the backwards compatibility... 

Are the any strong objections to that change? Are there users that we know are expecting the use of ``--count`` to print nothing (including to stderr where this goes)?

If there are still concerns, then I will hold off until we are ready for a 3.0 version, which may be coming (relatively) sooner rather than later.

**Comment by IanLee1521** [comment]
Going to close this in favor of the rebased, non-conflicting #543

**Comment by kampde** [comment]
I prefer to wait for the 3.0 release. What's the point on following a version number scheme if you are going to break it?

**Comment by IanLee1521** [comment]
Merged into the https://github.com/PyCQA/pycodestyle/tree/upcoming-3.0 branch for the 3.0 release

**Pull request closed without merging**
