### PR TITLE
Handle spaces around default operator in annotated and unannoated arguments.

### PR DESCRIPTION
**Pull request by clintonroy**

### CODE REVIEW

**Comment by webjunkie** [comment]
This also refs #692 and might be a duplicate of #717.

**Comment by taion** [comment]
Looks the same, yeah.

**Comment by clintonroy** [comment]
Very similar. I prefer my documentation changes. My implementation is a little more general, whether it's better or not is another question. Happy with either to go in.

**Comment by jayvdb** [comment]
https://github.com/PyCQA/pycodestyle/pull/717 was merged and released.  Are there improvements to it in your approach?

**Comment by clintonroy** [comment]
Nope. happy to close.

**Pull request closed without merging**
