### PR TITLE
Fix false-positive with star pattern

### LINKED ISSUE #1002: False positive E225 on initial PEP 634 star patterns
It's reported only when a star pattern is a very first pattern in a case clause.

```
match [42]:
    case *_, 42:  # E255 missing whitespace around operator
        pass
```

### PR DESCRIPTION
**Pull request by cdce8p**
Similar to #989: add ignore for soft keywords.

Closes #1002

### CODE REVIEW

**Review by asottile — APPROVED** [review]
whew, thanks for improving that condition as well -- it was *really* difficult to understand before this patch

**Comment by cdce8p** [comment]
Just noticed that the PR hasn't been merged yet. Do you need me to add anything else?

**Comment by cdce8p** [comment]
Any update now that `3.10` has been released?

**Comment by asottile** [comment]
we have a dual sign off process for merging PRs, but whatever ask for forgiveness rather than permission

**Pull request merged**
