### PR TITLE
 Support for custom indent sizes (tab widths) other than 4

### PR DESCRIPTION
**Pull request by ArgentFalcon**
Updates #206 so that it can be merged with current master
Also, adds unit tests and updates the docs properly

### CODE REVIEW

**Comment by tgy** [comment]
I am really interested in seeing this merged. Is anyone planning on merging this?

**Comment by tgy** [comment]
@iamaspacecow I proposed a PR on your fork with a rebase on PyCQA/pycodestyle master branch. Hope that helps.

**Comment by tgy** [comment]
@sigmavirus24 as @iamaspacecow is showing no sign of life, should I open a new PR with my branch (rebased on master)?

**Comment by sigmavirus24** [comment]
@tgy this branch does not need to be rebased. @iamaspacecow is not the blocker here.

**Comment by jdufresne** [comment]
What do you think about obtaining the indent size from a project's [`.editorconfig`](http://editorconfig.org/)?

**Comment by tgy** [comment]
@jdufresne to whom is your question directed to?

**Comment by jdufresne** [comment]
To all involved. To anyone interested in discussing or implementing the idea.

**Comment by tgy** [comment]
@jdufresne I personally love the idea!

**Comment by TD22057** [comment]
+1 - thanks for this.  I have a project with 500,000 SLOC of python that was started long before PEP8 and uses a 3 space indent.

**Comment by dannysauer** [comment]
Necromancy +1 :)

**Comment by jaydeep987** [comment]
how many centuries needed to merge this PR?!!

**Comment by valleedelisle** [comment]
I'd put a +1 here, but I'll put a -2 because I personally believe that 4 spaces indent is too much.

**Comment by asottile** [comment]
superseded by #970

**Pull request closed without merging**
