### PR TITLE
Refactor: remove the 'total_lines' variable from the 'trailing_blank_lines' check

### LINKED ISSUE #1142: W391: spurious warnings with python 3.12 beta
It appears there's an incompatibility with pycodestyle and python 3.12.0b1 (latest beta version).

You can check by running this in a docker container, this creates a minimal example showing this warning:
```
docker run --rm -ti python:3.12-rc /bin/bash
echo -en "import sys\n\nif 1:\n    pass\n" > test.py
pycodestyle test.py
```

Output is:
```
test.py:4:1: W391 blank line at end of file
```

Same with the git version of pycodestyle. This does not happen with python 3.11.

### PR DESCRIPTION
**Pull request by jayaddison**
May resolve #1142.

### CODE REVIEW

**Comment by pablogsal** [comment]
Give us one week or so because we may change this upstream (although I want to reiterate that we don't really need to).

**Comment by jayaddison** [comment]
Any interest in this as a cleanup despite the upstream fix, @asottile?  (I'm guessing not, and will likely delete the branch/fork soon, but figured it'd be worth checking)

**Comment by asottile** [comment]
it has a correctness issue so probably not

(with blank line at end)

```python
print(1)


print(2)


print(3)

```

```console
$ python3 -m pycodestyle t.py
t.py:1:1: W391 blank line at end of file
t.py:2:1: W391 blank line at end of file
t.py:3:1: W391 blank line at end of file
t.py:4:1: W391 blank line at end of file
t.py:5:1: W391 blank line at end of file
t.py:6:1: W391 blank line at end of file
t.py:7:1: W391 blank line at end of file
t.py:8:1: W391 blank line at end of file
```

**Comment by jayaddison** [comment]
Hehe, ok - yep, that definitely settles it.  Thank you.

**Comment by jayaddison** [comment]
(I did test it in combination with `flake8-pyi`, but evidently missed whatever issue that is.  I _might_ take another look, probably not though)

**Comment by jayaddison** [comment]
It's because it runs once per-line, of course.  Never mind, ignore me.  I seem to be getting worse and worse at computers.

**Pull request closed without merging**
