### PR TITLE
Add E252 on missing whitespace for annotated parameter defaults

### PR DESCRIPTION
**Pull request by taion**
Closes https://github.com/PyCQA/pycodestyle/issues/692

### CODE REVIEW

**Comment by taion** [comment]
Any update here?

**Comment by taion** [comment]
Ping.

**Comment by webjunkie** [comment]
@sigmavirus24 can you check if this is okay?

**Comment by sigmavirus24** [comment]
Thank you for your contribution and patience. Sorry it took so long to get 'round to.

**Comment by taion** [comment]
No worries! Thanks to you as well.

**Pull request merged**
