### PR TITLE
Fix problem with treating ~ operator as binary.

### LINKED ISSUE #384: Tilde is treated as binary operator
Following code cause W503 to be reported, because ~ is treated as a binary operator, where in reality it is unary.
```
var = (1 &
       ~2)
```

### PR DESCRIPTION
**Pull request by czyzykowski**
Fixes #384

### CODE REVIEW

**Comment by mbarrien** [comment]
Ping on getting this merged? Affecting my projects.

**Comment by Incognito** [comment]
Any chance this can get merged? @IanLee1521 @Nurdok @PCManticore @sigmavirus24 (@-ing people public on the PyCQA org).

**Comment by sigmavirus24** [comment]
@Incognito the only people who are allowed to merge pull requests here are @IanLee1521 and myself. Please don't try to @-mention the entire organization.

As for this pull request, the original issue has people claiming this is an incomplete fix. If you want to make sure this is fixed, could you verify that concern? If this works for your case and the other cases described there, I'll be happy to merge it if @IanLee1521 can't get around to it.

**Comment by sigmavirus24** [comment]
IMO, the person saying this didn't fix the case with `-` seems to be incorrect. The docstring tests clearly test that case so I think that case is already covered. This also looks to fix the original bug. I'll try to test this tonight.

**Comment by IanLee1521** [comment]
So I looked at it, and it there is a warning if you add a doctest of `Okay: var = (1 &\n       -2)` or `Okay: var = (1 *\n       -2)`, the W503 warning does pop up. I'm going to open a separate issue for that, and merge / close this one which is specific to the `~` operator.

**Comment by Incognito** [comment]
Thanks for getting this through! I appreciate having this fix.

**Pull request merged**
