### PR TITLE
change help name from pep8 to pycodestyle

### PR DESCRIPTION
**Pull request by xiaopeng163**
#518 
Signed-off-by: Peng Xiao <xiaoquwl@gmail.com>

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Hi @xiaopeng163 

Thanks for sending this pull request! It's definitely a step in the right direction. You should notice, however, that the tests are failing on one minor thing. If you could fix that up, we should be able to merge this and close this issue up.

**Comment by IanLee1521** [comment]
Specifically, this is the issue: https://travis-ci.org/PyCQA/pycodestyle/jobs/134339102#L157

**Comment by xiaopeng163** [comment]
Thanks for information

I have a trouble for this error:

```
======================================================================
FAIL: test_styleguide_options (testsuite.test_api.APITestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PyCQA/pycodestyle/testsuite/test_api.py", line 169, in test_styleguide_options
    self.assertEqual(pep8style.options.ignore, ('E226', 'E24'))
AssertionError: Tuples differ: ('E121', 'E123', 'E126', 'E226... != ('E226', 'E24')
First differing element 0:
E121
E226
First tuple contains 5 additional elements.
First extra element 2:
E126
- ('E121', 'E123', 'E126', 'E226', 'E24', 'E704', 'W503')
+ ('E226', 'E24')
----------------------------------------------------------------------
```

**Comment by sigmavirus24** [comment]
How does this differ from #530 and #535?

**Pull request closed without merging**
